### ISSUE TITLE
Some Discord webhooks do not work for me

### ISSUE THREAD

**Issue by Justin2211** [SnailyCAD/snaily-cadv4#1271]
### What version of Node.js are you using?

v16.18.1

### What version of npm are you using?

8.19.2

### What operating system are you using?

Linux Debian 11

### What version of SnailyCAD are you currently using?

Newest commit (80e6c57)

### Describe the Bug

Unfortunately, the following webhooks do not trigger Discord notification for me:
- Panic

citizen records webhook I have not tested yet.

### Expected Behavior

That a Discord notification is sent that a panic button has been triggered.

### To Reproduce

Set Webook Channel for Panic under: Admin -> CAD Settings -> Discord Webhooks -> "Panic button channel".

**Comment by Dev-CasperTheGhost** [comment]
Are you able to share the channel integrations tab? Where all the webhooks are listed, I want to see if there's any duplicated ones or unnecessary ones.

**Comment by Justin2211** [comment]
Sure,

![1](https://user-images.githubusercontent.com/36715641/205296047-40863ea0-ea00-4bdb-941f-b8e0500939c1.png)
![2](https://user-images.githubusercontent.com/36715641/205296250-e0fd6615-016f-4e0c-8cf7-edf32b94a889.png)

Sincerely

**Comment by Dev-CasperTheGhost** [comment]
Are you able to test other webhooks? Just to make sure it's only the panic button webhook

**Comment by Justin2211** [comment]
Okay, I have tested it.
All webhooks work except Panic.

Sincerely

**Comment by Dev-CasperTheGhost** [comment]
Fixed now!

**Comment by Justin2211** [comment]
Good evening, I have now tested it again but unfortunately again without success.

My friend has also tried it.

If I click on Officer -> Dashboard, then set myself to On Duty and then click on "Panic Button", usually nothing happens and I get no message in CAD.

Then I have to click again on Officer -> Dashboard and can then trigger the Panic Button.

But the Discord notification still doesn't work for my friend and me.

I have already tried to delete the webhook in SnailyCAD, then save it and set it again. But even then no Discord message comes.

Translated with www.DeepL.com/Translator (free version)

**Comment by Dev-CasperTheGhost** [comment]
Does it work if you select the panic button ten-code? Not the "Panic Button" button?

**Comment by Justin2211** [comment]
Thank you very much, it works now.
I had to create another 10-code panic button which is connected to the original "Panic Button" button.

Now as soon as you toggle one of the two it works.

Sincerely.
